[language-server.ltex-ls-plus]
config = { ltex = { language = "en-US", enabled = [
  "bibtex", "context", "context.tex", "html", "latex", "markdown", "mdx",
  "typst", "asciidoc", "neorg", "org", "quarto", "restructuredtext", "rsweave",
  "javascript",
] } }

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "ltex-ls-plus",
]
